### ISSUE TITLE
【@solid-mediakit/auth】SessionProvider throw Error

### ISSUE THREAD

**Issue by oligamiq** [solidjs-community/mediakit#10]
SessionProvider > getSession > createReqWithServerHandler
throw Error on it so SessionProvider throw error.
I use cloudflare pages adapter but return error code so made bug
※cloudflare deploy server made error only because cloudflare throwing error info to response I think
```
Uncaught (in promise) SyntaxError: Unexpected token 'e', "error code: 1003" is not valid JSON
    at async /functionsWorker-0.549692055662389.js:9367:18
    at async /functionsWorker-0.549692055662389.js:9327:30
```
context value is error code so window cannot load.

I wrapping SessionProvider code in library so ok.
Could you wrap throwing error?

**Comment by OrJDev** [comment]
please reopen if you face this issue in the new version
