### ISSUE TITLE
Unexpected token 'N', "Not Found" is not valid JSON

### ISSUE THREAD

**Issue by levma** [solidjs-community/mediakit#103]
Refering to https://github.com/solidjs/solid-start/issues/1627

With `@solid-mediakit/auth` `v2.1.3` and `@auth/core` `v0.35.0` I can not run my project no more.

Steps to reproduce:

1. create a new project with: `bun create solid`
2. choose authjs
3. set a value for AUTH_SECRET and your auth provider secrets in `.env` file
4. fill in config in src/src/auth.ts (in my case: GoogleProvider)
5. run `bun dev`
6. goto http://localhost:3000
7. you will see `Unexpected token 'N', "Not Found" is not valid JSON`

It has something to do with this commit:
https://github.com/solidjs-community/mediakit/commit/fd8def1c0aed31f45f6541a7b4a0e2453810e92e#diff-5d3f2d4bff4dae314e2e8f7a5668bb0e09bcf57b71e4bff8ba0ac266e5a13391R81

The error is thrown here:
https://github.com/solidjs-community/mediakit/blob/25d9acb8162167d927b87b3a7e740df666316e1d/packages/auth/solid/src/client.tsx#L229

I tried to set VITE_AUTH_PATH=/api/auth in `.env` but the problem persisted.

I've successfully set `config.basePath` to `'/api/auth'` in src/server/auth.ts and this resolved my problem.

**Comment by OrJDev** [comment]
Hey there, can you please remove VITE_AUTH_PATH from your .env and instead add the path to the auth url.

ie:
```
AUTH_URL=http://localhost:3000
VITE_AUTH_PATH=/api/auth
```

should become:

```
AUTH_URL=http://localhost:3000/api/auth
```

also plese upgrade to the latest released version of solid-auth.

**Comment by OrJDev** [comment]
yes you are right

> I've successfully set config.basePath to '/api/auth' in src/server/auth.ts and this resolved my problem.

this is required and i also added it to the docs so people would know that, ty.
