### ISSUE TITLE
How to access Tanstack Query properties is undocumented

### ISSUE THREAD

**Issue by NextMerge** [solidjs-community/mediakit#104]
Given the following code:

```
const testQuery = builder$().query$(() => {
    return "foo";
}, "testQuery");

const testQuery2 = query$({
    queryFn: () => {
        return "foo";
    },
    key: "testQuery2",
});
```

It doesn't seem like it's possible to access any of the extended Tanstack Query properties in either situation.

Specifically any of these besides the query function and key: https://tanstack.com/query/latest/docs/framework/solid/reference/createQuery#query-options---accessorqueryoptions

**Comment by NextMerge** [comment]
After looking through the source code I figured out that you can access the properties through the second parameter when using the query in a component. It's just not documented. Either showing an example of that or clarifying that `query$()` is actually creating a factory to build a query in each component it's called in would be nice. I can create a PR for that later.

Only thing I find weird is that properties need to be defined through the return value of a function. Is there a reason for that?

**Comment by OrJDev** [comment]
merged,ty

**Comment by OrJDev** [comment]
> After looking through the source code I figured out that you can access the properties through the second parameter when using the query in a component. It's just not documented. Either showing an example of that or clarifying that `query$()` is actually creating a factory to build a query in each component it's called in would be nice. I can create a PR for that later.


I just noticed your sponsor, i didn't get any notification. 
I couldn't find anywhere to send you a message (no social is linked to your profile). 
I truly appreciate your sponsor it helps me a lot in this period of time, lmk if you need anything. Ty man.
