### ISSUE TITLE
Updated Auth@3.0.0, export named "parse" is not provided by the underlying jwt.js dependency

### ISSUE THREAD

**Issue by joeygrable94** [solidjs-community/mediakit#121]
Uncaught SyntaxError: The requested module '/_build/@fs/path/to/node_modules/.pnpm/cookie@0.7.1/node_modules/cookie/index.js?v=8959e822' does not provide an export named 'parse' (at jwt.js?v=8959e822:42:10)

**Comment by 0-don** [comment]
how did you fix

**Comment by 0-don** [comment]
@OrJDev is there a particular reason why `@auth/core` needs to be that version 
![image](https://github.com/user-attachments/assets/8a4a8c38-2805-413e-9f3d-f09f5a4e93bd)
because if using latest it throws this error in browser console

**Comment by OrJDev** [comment]
> @OrJDev
> 
> is there a particular reason why `@auth/core` needs to be that version 
> 
> ![image](https://github.com/user-attachments/assets/8a4a8c38-2805-413e-9f3d-f09f5a4e93bd)
> 
> because if using latest it throws this error in browser console

I locked it because they broke something in the core, i tried opening an issue but their bot keeps on automatically closing my issues because they don't have enough info
