### ISSUE TITLE
Adding authVite plugin to defineConfig has typescript error

### ISSUE THREAD

**Issue by paulo-assoc** [solidjs-community/mediakit#122]
The error is: Type 'Plugin<any>' is not assignable to type 'PluginOption'. Types of property 'apply' are incompatible.

![Screenshot 2024-10-22 143245](https://github.com/user-attachments/assets/4dda7d30-32c6-4cf5-9b00-b6debe5baf9f)

**Comment by paulo-assoc** [comment]
Thanks, @OrJDev!

**Comment by OrJDev** [comment]
> Thanks, @OrJDev!

what vite version are you using? i'm currently using the latest and it seems to work
