### ISSUE TITLE
【@solid-mediakit/trpc】it seems that the output type of useInfiniteQuery is wrong 

### ISSUE THREAD

**Issue by Frank-III** [solidjs-community/mediakit#13]
**Issue**
The returned query type of useInfiniteQuery seems wrong, I cannot get `query.data.pages` instead I get: 
<img width="799" alt="image" src="https://github.com/solidjs-community/mediakit/assets/73262844/0bce1c54-cfcb-46b6-9ba1-9a582b230079">

**Possible reason:**
we have:
```ts
export type UseTRPCInfiniteQueryResult<TData, TError> = CreateInfiniteQueryResult<TData, TError> & TRPCHookResult;
```
but in trpc repo:
```ts
export type UseTRPCInfiniteQueryResult<TData, TError, TInput> = TRPCHookResult &
  UseInfiniteQueryResult<
    InfiniteData<TData, NonNullable<ExtractCursorType<TInput>> | null>,
    TError
  >;
```

Maybe wrap `TData` with `InfiniteData` would fix it? I would take a look, and hopefully submit a pr

**Comment by OrJDev** [comment]
pr was opened, closing.
