### ISSUE TITLE
import "query" for _$$getUser is missing

### ISSUE THREAD

**Issue by vincehi** [solidjs-community/mediakit#134]
after transforming a ‘protected$’ page, the query import is missing

**Comment by OrJDev** [comment]
you need to install the latest `@solidjs/router` since it was renamed from `cache` to `query`

lmk if that works

**Comment by vincehi** [comment]
I'm already using the latest version of @solidjs/router, so that's not the problem. The authVite plugin doesn't add query import.

**Comment by OrJDev** [comment]
I see the issue. 

It still imports cache instead of query

```ts
babelUtils.importIfNotThere(path, t, 'cache', '@solidjs/router')
```

**Comment by thatgurkangurk** [comment]
is there a fix for this? I’m getting the same issue
