### ISSUE TITLE
@solid-mediakit/trpc: is it possible to use trpc without solid-start?

### ISSUE THREAD

**Issue by Frank-III** [solidjs-community/mediakit#15]
Sorry I may be n00b, is it possible to use trpc without solid-start? like using hono-js as backend and use trpc middleware, then use trpc on the front-end(just like trpc has `createTRPCReact`, can we have `createTRPCSolid`?

**Comment by OrJDev** [comment]
i believe this is what you are looking for https://github.com/OrJDev/solid-trpc/tree/next

**Comment by shiro** [comment]
The project is archived, could this be supported here instead and share code with start's solution as much as possible?  
I.e. exporting both `createTRPCSolidStart` and `createTRPCSolid` sounds reasonable.

**Comment by shiro** [comment]
Is it possible to re-open this in order to track supporting standalone solid-js at some point in the future, or does this repo only focus on solid-start?

Based on the current description (`A set of utilities to use with your Solid apps.`) it seems like its in scope?
