### ISSUE TITLE
Recreating tRPC client breaks batching

### ISSUE THREAD

**Issue by charlie-hadden** [solidjs-community/mediakit#22]
Hi there - thanks for your work on this!

In `packages/trpc/src/shared/hooks/createHooksInternal.tsx` there are multiple places where a new tRPC client is created, such as:
https://github.com/solidjs-community/mediakit/blob/bd9072570be0378e00d8ffe7eea4d33643355caf/packages/trpc/src/shared/hooks/createHooksInternal.tsx#L198

Because of this, things like the batch link don't work correctly. I can put together a reproduction for you if it's useful but I think it's fairly self explanatory. Creating the client once and storing it in the context along with the `queryClient` seems to work correctly, but I'm not sure if there's a different reason that you're currently initializing a new client each time.

**Comment by OrJDev** [comment]
Hey there please try again now with the new version 

create jd app - https://github.com/OrJDev/create-jd-app/releases/tag/v2.2.0
https://github.com/solidjs-community/mediakit/releases/tag/%40solid-mediakit%2Ftrpc%403.0.0
