### ISSUE TITLE
solid query not handling errors when server side rendering

### ISSUE THREAD

**Issue by shiro** [solidjs-community/mediakit#27]
When an error is thrown inside of TRPC resolvers, the solid start app crashes.

I already asked Ryan about this on Discord, apparently TRPC includes the `Request` object on the error type, here's some chat excerpts:
```
ryansolid: Looks like they just return a response object with some stuff on the body.. let me see
ryansolid: Ok yeah it's on the client side
ryansolid: we don't need a custom fetch.. it's that when we try to handle the error coming back from TRPC we can't serialize it
ryansolid: They put a bunch of stuff like the Response body of the request on it
ryansolid: And when we try to serialize that well.. we get the error you saw
ryansolid: I fixed it by wrapping my request in a try/catch and making my own error from their error
ryansolid: Not particularly convenient.. I guess this is an argument for wrapping the fetcher
shiro: can you share the catch block? that would be really helpful for a quick-fix to stop it from crashing 😄
ryansolid: I mean just did new Error(err.message)
...
ryansolid: the problem is err.meta
ryansolid: it puts the Response on it and we can't serialize that
ryansolid: The problem is everyone's error objects are arbitrary so there is no generic way for me to sanitize it
...
shiro: where did you put the try-catch?
ryansolid: I did it at the call point
ryansolid: Like in `createAsync`
```

Could mediakit remove the non-seriazable stuff from the error or wrap errors to fix this?

**Steps to reproduce:**
- spin up a new create-jd-app
- add the line `throw new Error("something broke");` inside a resolver in `src/server/trpc/router/example.ts`
- open the browser
- observe app crash

**output:**
```
B [Error]: Seroval caught an error during the parsing process.

Error
Seroval caught an error during the parsing process.

Error
Seroval caught an error during the parsing process.

TypeError
Response.clone: Body has already been consumed.

- For more information, please check the "cause" property of this error.
- If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new

- For more information, please check the "cause" property of this error.
- If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new

- For more information, please check the "cause" property of this error.
- If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new
    at J.parse (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:32248)
    at J.parseWithError (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:36321)
    at file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:35487 {
  cause: B [Error]: Seroval caught an error during the parsing process.

  Error
  Seroval caught an error during the parsing process.

  TypeError
  Response.clone: Body has already been consumed.

  - For more information, please check the "cause" property of this error.
  - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new

  - For more information, please check the "cause" property of this error.
  - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new
      at J.parse (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:32248)
      at J.parseProperties (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:34746)
      at J.parseError (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:29840)
      ... 3 lines matching cause stack trace ...
      at file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:35487 {
    cause: B [Error]: Seroval caught an error during the parsing process.
```

**Comment by OrJDev** [comment]
> When an error is thrown inside of TRPC resolvers, the solid start app crashes.
> 
> 
> 
> I already asked Ryan about this on Discord, apparently TRPC includes the `Request` object on the error type, here's some chat excerpts:
> 
> ```
> 
> ryansolid: Looks like they just return a response object with some stuff on the body.. let me see
> 
> ryansolid: Ok yeah it's on the client side
> 
> ryansolid: we don't need a custom fetch.. it's that when we try to handle the error coming back from TRPC we can't serialize it
> 
> ryansolid: They put a bunch of stuff like the Response body of the request on it
> 
> ryansolid: And when we try to serialize that well.. we get the error you saw
> 
> ryansolid: I fixed it by wrapping my request in a try/catch and making my own error from their error
> 
> ryansolid: Not particularly convenient.. I guess this is an argument for wrapping the fetcher
> 
> shiro: can you share the catch block? that would be really helpful for a quick-fix to stop it from crashing 😄
> 
> ryansolid: I mean just did new Error(err.message)
> 
> ...
> 
> ryansolid: the problem is err.meta
> 
> ryansolid: it puts the Response on it and we can't serialize that
> 
> ryansolid: The problem is everyone's error objects are arbitrary so there is no generic way for me to sanitize it
> 
> ...
> 
> shiro: where did you put the try-catch?
> 
> ryansolid: I did it at the call point
> 
> ryansolid: Like in `createAsync`
> 
> ```
> 
> 
> 
> Could mediakit remove the non-seriazable stuff from the error or wrap errors to fix this?
> 
> 
> 
> **Steps to reproduce:**
> 
> - spin up a new create-jd-app
> 
> - add the line `throw new Error("something broke");` inside a resolver in `src/server/trpc/router/example.ts`
> 
> - open the browser
> 
> - observe app crash
> 
> 
> 
> **output:**
> 
> ```
> 
> B [Error]: Seroval caught an error during the parsing process.
> 
> 
> 
> Error
> 
> Seroval caught an error during the parsing process.
> 
> 
> 
> Error
> 
> Seroval caught an error during the parsing process.
> 
> 
> 
> TypeError
> 
> Response.clone: Body has already been consumed.
> 
> 
> 
> - For more information, please check the "cause" property of this error.
> 
> - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new
> 
> 
> 
> - For more information, please check the "cause" property of this error.
> 
> - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new
> 
> 
> 
> - For more information, please check the "cause" property of this error.
> 
> - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new
> 
>     at J.parse (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:32248)
> 
>     at J.parseWithError (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:36321)
> 
>     at file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:35487 {
> 
>   cause: B [Error]: Seroval caught an error during the parsing process.
> 
> 
> 
>   Error
> 
>   Seroval caught an error during the parsing process.
> 
> 
> 
>   TypeError
> 
>   Response.clone: Body has already been consumed.
> 
> 
> 
>   - For more information, please check the "cause" property of this error.
> 
>   - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new
> 
> 
> 
>   - For more information, please check the "cause" property of this error.
> 
>   - If you believe this is an error in Seroval, please submit an issue at https://github.com/lxsmnsyc/seroval/issues/new
> 
>       at J.parse (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:32248)
> 
>       at J.parseProperties (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:34746)
> 
>       at J.parseError (file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:29840)
> 
>       ... 3 lines matching cause stack trace ...
> 
>       at file:///home/shiro/tmp/foo/my-app/node_modules/seroval/dist/esm/production/index.mjs:17:35487 {
> 
>     cause: B [Error]: Seroval caught an error during the parsing process.
> 
> ```

This isn't an issue in trpc, that's Solid Query not handling errors correctly when Server Side Rendering. You can try again with ssr off and see that it works find.


Cc @ardeora

**Comment by shiro** [comment]
Thanks for the triage.
@ardeora is there any tracking issue for this already? Really appreciate it :bow:

**Comment by OrJDev** [comment]
cc @ardeora

**Comment by ardeora** [comment]
@shiro @OrJDev Apologies for the late fix. But I think I have applied a fix to this. Please let me know if you still face an issue. If you still face any issues, a simple codesandbox/stackblitz reproduction would be awesome to quickly fix the issue. Hope you both have an amazing week! 😄

**Comment by OrJDev** [comment]
Thanks @ardeora,

https://github.com/solidjs-community/mediakit/commit/edcd61313ab67f44d281d3b9d839b91a9545bd63

@shiro reopen if you still face this.

**Comment by OrJDev** [comment]
Reopening because this was broken again in the new solidstart

**Comment by OrJDev** [comment]
Well using ErrorBoundary is the recommended way for now
