### ISSUE TITLE
[auth] Peer dependency warnings

### ISSUE THREAD

**Issue by birkskyum** [solidjs-community/mediakit#47]
WARN  Issues with peer dependencies found
.
└─┬ @solid-mediakit/auth 2.0.7
  ├── ✕ unmet peer @solidjs/start@^0.7.4: found 1.0.0-rc.0
  ├── ✕ unmet peer typescript@^4.8.2: found 5.4.4
  └── ✕ unmet peer @auth/core@^0.28.0: found 0.29.0

**Comment by OrJDev** [comment]
https://github.com/solidjs-community/mediakit/commit/8a3ce95528bbfd174e99a511967b9d28200b3067

note you still have to use the latest solid-start version to prevent this, but the typescript / core should be fixed
