### ISSUE TITLE
import { signOut } from "@solid-mediakit/auth"; gives error.

### ISSUE THREAD

**Issue by birkskyum** [solidjs-community/mediakit#60]
It's a bit troublesome that signOut can be imported from both

import { signOut } from "@solid-mediakit/auth";

and 

import { signOut } from "@solid-mediakit/auth/client";

but that only the latter won't break ones code.

**Comment by OrJDev** [comment]
> It's a bit troublesome that signOut can be imported from both
> 
> 
> 
> import { signOut } from "@solid-mediakit/auth";
> 
> 
> 
> and 
> 
> 
> 
> import { signOut } from "@solid-mediakit/auth/client";
> 
> 
> 
> but that only the latter won't break ones code.

The first signOut is for the server, i don't think its necessary to even export that as it has no use currently, but yes it just a utility for the server. I should probably make a pr when im able to and un-export that.

**Comment by OrJDev** [comment]
this was fixed in latest version, renamed the server sign in / out.
