### ISSUE TITLE
SSR fetch resource while on protected$ route

### ISSUE THREAD

**Issue by joeygrable94** [solidjs-community/mediakit#67]
I am having difficulty messing this library with the routing definitions provided by SolidStart's docs.

Has anyone successfully incorporated a resource fetch on the server while on a protected$ route?

This is not my exact code, but shows what I am trying to do essentially.

```
import { RouteDefinition, RouteSectionProps, createAsync } from '@solidjs/router';
import { protected$ } from '@solid-mediakit/auth';

export const route = {
  load({ location }) {
    void ssrFetchClientsList(+location.query.page || 1, +location.query.size || 10);
  }
} satisfies RouteDefinition;

export default protected$((session$) => {
  const page = () => 1;
  const size = () => 10;
  const data = createAsync(() => ssrFetchClientsList(page(), size()));

  return (
    <main>
      <h1>Protected Route</h1>
      <h1>hello {session$.user?.name}</h1>
    </main>
  )
}, '/login')
```

**Comment by OrJDev** [comment]
> I am having difficulty messing this library with the routing definitions provided by SolidStart's docs.
> 
> 
> 
> Has anyone successfully incorporated a resource fetch on the server while on a protected$ route?
> 
> 
> 
> This is not my exact code, but shows what I am trying to do essentially.
> 
> 
> 
> ```
> 
> import { RouteDefinition, RouteSectionProps, createAsync } from '@solidjs/router';
> 
> import { protected$ } from '@solid-mediakit/auth';
> 
> 
> 
> export const route = {
> 
>   load({ location }) {
> 
>     void ssrFetchClientsList(+location.query.page || 1, +location.query.size || 10);
> 
>   }
> 
> } satisfies RouteDefinition;
> 
> 
> 
> export default protected$((session$) => {
> 
>   const page = () => 1;
> 
>   const size = () => 10;
> 
>   const data = createAsync(() => ssrFetchClientsList(page(), size()));
> 
> 
> 
>   return (
> 
>     <main>
> 
>       <h1>Protected Route</h1>
> 
>       <h1>hello {session$.user?.name}</h1>
> 
>     </main>
> 
>   )
> 
> }, '/login')
> 
> ```

Sorry for the late response not sure why i didn't get a notification. Basically protected$ in the babel plugin exports a routeData with session logic, so when you specify a routeData in addition to protected$ you basically create 2 route data, meaning you can't export routeData function while using the protected$ method. Im still trying to get over it but not sure how.

**Comment by OrJDev** [comment]
> > I am having difficulty messing this library with the routing definitions provided by SolidStart's docs.
> > 
> > 
> > 
> > Has anyone successfully incorporated a resource fetch on the server while on a protected$ route?
> > 
> > 
> > 
> > This is not my exact code, but shows what I am trying to do essentially.
> > 
> > 
> > 
> > ```
> > 
> > import { RouteDefinition, RouteSectionProps, createAsync } from '@solidjs/router';
> > 
> > import { protected$ } from '@solid-mediakit/auth';
> > 
> > 
> > 
> > export const route = {
> > 
> >   load({ location }) {
> > 
> >     void ssrFetchClientsList(+location.query.page || 1, +location.query.size || 10);
> > 
> >   }
> > 
> > } satisfies RouteDefinition;
> > 
> > 
> > 
> > export default protected$((session$) => {
> > 
> >   const page = () => 1;
> > 
> >   const size = () => 10;
> > 
> >   const data = createAsync(() => ssrFetchClientsList(page(), size()));
> > 
> > 
> > 
> >   return (
> > 
> >     <main>
> > 
> >       <h1>Protected Route</h1>
> > 
> >       <h1>hello {session$.user?.name}</h1>
> > 
> >     </main>
> > 
> >   )
> > 
> > }, '/login')
> > 
> > ```
> 
> Sorry for the late response not sure why i didn't get a notification. Basically protected$ in the babel plugin exports a routeData with session logic, so when you specify a routeData in addition to protected$ you basically create 2 route data, meaning you can't export routeData function while using the protected$ method. Im still trying to get over it but not sure how because Start doesn't allow exporting multiple functions, and if the session logic isn't handled in the routeData (eg. creating it within the page) it creates waterfalls

**Comment by joeygrable94** [comment]
My question should probably go into a discussion tab rather than an issue. I see what you are saying now, and I can get my authorized routes to load the session and fetch restricted data from the API. Thank you for looking into it!

**Comment by OrJDev** [comment]
> My question should probably go into a discussion tab rather than an issue. I see what you are saying now, and I can get my authorized routes to load the session and fetch restricted data from the API. Thank you for looking into it!

Yes so basically in your route load use a server function that will get the session and redirect if there is no user, In additional to that fetch the data you want from your own functions. Here is an example output for our protected$ function so you could understand better what went wrong.


```tsx

import { authOptions } from '~/server/auth'
import { Show } from 'solid-js'
import { getSession } from '@solid-mediakit/auth'
import { getRequestEvent } from 'solid-js/web'
import { createAsync } from '@solidjs/router'
import { redirect } from '@solidjs/router'
import { cache } from '@solidjs/router'
import { protected$ } from '@solid-mediakit/auth'

const _$$getUser = cache(async () => {
  'use server'

  const event = getRequestEvent()
  const session = await getSession(event.request, authOptions)
  if (!session) {
    throw redirect('/')
  }
  return session
}, 'media-user')

export default () => {
  const _$$session = createAsync(() => _$$getUser())
  const _$$RenderProtected = () => {
    return (
      <main>
        <h1>Protected Route</h1>
        <h1>hello {_$$session().user?.name}</h1>
      </main>
    )
  }
  return (
    <Show when={_$$session()?.user}>
      <_$$RenderProtected />
    </Show>
  )
}
```
