### ISSUE TITLE
doc: the usage of sigh out is same as sign in 

### ISSUE THREAD

**Issue by Huliiiiii** [solidjs-community/mediakit#84]
https://github.com/solidjs-community/mediakit/blob/6162890dd2f81e903dcb98129c85797bb8efeea6/docs/src/content/docs/auth/signOut.mdx?plain=1#L1-L19

**Comment by OrJDev** [comment]
im not sure what is the issue here, could you explain please

**Comment by OrJDev** [comment]
please reopen when you are able to

**Comment by Huliiiiii** [comment]
@OrJDev 
The usages are about sign in, not sign out.

**Comment by OrJDev** [comment]
Ah thank you for that, fixed in

https://github.com/solidjs-community/mediakit/commit/b0fcae128482b2f911d18ac8d599061ef4a41b46
